name: build_executable

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Compile
      run: make test

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}-${{ matrix.os }}
        name: Release ${{ matrix.os }} Build ${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          client
          server
